# Basic Github Action Secret access
# What it does:
#  - Run job to access Repo secrets
#  - Request approval for job that access Environment secrets
name: accessing-secrets
on:
  push:
    branches:
      # You can specify multi branch
      - main
      - develop
jobs:
  repo-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access repo secrets
        run: |
          echo "This will list available secrets defined in Repo > Settings"
          echo "By default the values are redacted"
          echo "${{ toJson(secrets) }}"
  repo-environments-secrets:
    runs-on: ubuntu-latest
    environment:
      # environment_A was defined in the Repo Settings page > Environments
      name: environment_A
    steps:
      - name: Access environment secrets
        run: |
          echo "By the time the step runs. That means the job has been approved to access the secrets"
          echo "Secrets will contains environment secrets and repo secrets"
          echo "${{ toJson(secrets) }}"